import { Server, Database, Key, Activity, HardDrive, FileText, Terminal, Layers, Shield, FolderOpen, GitMerge, Globe, Brain, Download, Settings, Bot, LayoutDashboard } from 'lucide-react';
import ServerManager from '@/components/apps/ServerManager';
import DatabaseManager from '@/components/apps/DatabaseManager';
import ApiKeyManager from '@/components/apps/ApiKeyManager';
import IntegrationMonitor from '@/components/apps/IntegrationMonitor';
import BackupManager from '@/components/apps/BackupManager';
import LogsViewer from '@/components/apps/LogsViewer';
import DeveloperTerminal from '@/components/apps/DeveloperTerminal';
import DB from '@/components/apps/DB';
import VpcAuth from '@/components/apps/VpcAuth';
import Gallery from '@/components/apps/Gallery';
import WebHosting from '@/components/apps/WebHosting';
import VPSHub from '@/components/apps/VPSHub';
import AgentSettings from '@/components/apps/AgentSettings';
import JarvisChat from '@/components/apps/JarvisChat';
import VpcStore from '@/components/apps/VpcStore';
import SystemSettings from '@/components/apps/SystemSettings';
import Pipeline from '@/components/apps/Pipeline';

const APP_REGISTRY = {
  'pipeline': {
    id: 'pipeline',
    title: 'Pipeline',
    description: 'Grouped Resources',
    icon: LayoutDashboard,
    iconColor: 'text-rose-400',
    iconBg: 'bg-rose-500/15',
    category: 'development',
    component: Pipeline,
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 900,
    minHeight: 550,
  },
  'vpshub': {
    id: 'vpshub',
    title: 'VPSHub',
    description: 'Code, Deploy & Collaborate',
    icon: GitMerge,
    iconColor: 'text-violet-400',
    iconBg: 'bg-violet-500/15',
    category: 'development',
    component: VPSHub,
    defaultWidth: 1200,
    defaultHeight: 750,
    minWidth: 800,
    minHeight: 500,
  },
  'db': {
    id: 'db',
    title: 'DB',
    description: 'Database Projects',
    icon: Layers,
    iconColor: 'text-emerald-400',
    iconBg: 'bg-emerald-500/15',
    category: 'development',
    component: DB,
    permission: 'db',
    defaultWidth: 1200,
    defaultHeight: 700,
    minWidth: 900,
    minHeight: 550,
  },
  'web-hosting': {
    id: 'web-hosting',
    title: 'Web Hosting',
    description: 'Deploy & Host Sites',
    icon: Globe,
    iconColor: 'text-blue-400',
    iconBg: 'bg-blue-500/15',
    category: 'development',
    component: WebHosting,
    permission: 'web_hosting',
    defaultWidth: 1100,
    defaultHeight: 700,
    minWidth: 800,
    minHeight: 500,
  },
  'database-manager': {
    id: 'database-manager',
    title: 'Database Manager',
    description: 'PostgreSQL Browser',
    icon: Database,
    iconColor: 'text-cyan-400',
    iconBg: 'bg-cyan-500/15',
    category: 'infrastructure',
    component: DatabaseManager,
    permission: 'databases',
    defaultWidth: 1200,
    defaultHeight: 700,
    minWidth: 800,
    minHeight: 500,
  },
  'server-manager': {
    id: 'server-manager',
    title: 'Server Manager',
    description: 'Processes & Disk',
    icon: Server,
    iconColor: 'text-orange-400',
    iconBg: 'bg-orange-500/15',
    category: 'infrastructure',
    component: ServerManager,
    permission: 'servers',
    defaultWidth: 1000,
    defaultHeight: 650,
    minWidth: 600,
    minHeight: 400,
  },
  'developer-terminal': {
    id: 'developer-terminal',
    title: 'Terminal',
    description: 'Command Line',
    icon: Terminal,
    iconColor: 'text-green-400',
    iconBg: 'bg-green-500/15',
    category: 'infrastructure',
    component: DeveloperTerminal,
    permission: 'terminal',
    defaultWidth: 800,
    defaultHeight: 500,
    minWidth: 500,
    minHeight: 300,
  },
  'logs-viewer': {
    id: 'logs-viewer',
    title: 'Logs',
    description: 'Application Logs',
    icon: FileText,
    iconColor: 'text-yellow-400',
    iconBg: 'bg-yellow-500/15',
    category: 'infrastructure',
    component: LogsViewer,
    permission: 'logs',
    defaultWidth: 1000,
    defaultHeight: 600,
    minWidth: 600,
    minHeight: 400,
  },
  'vpc-auth': {
    id: 'vpc-auth',
    title: 'VPC Auth',
    description: 'Users & Roles',
    icon: Shield,
    iconColor: 'text-indigo-400',
    iconBg: 'bg-indigo-500/15',
    category: 'system',
    component: VpcAuth,
    permission: 'users',
    defaultWidth: 900,
    defaultHeight: 600,
    minWidth: 600,
    minHeight: 400,
  },
  'api-key-manager': {
    id: 'api-key-manager',
    title: 'API Keys',
    description: 'Manage Credentials',
    icon: Key,
    iconColor: 'text-amber-400',
    iconBg: 'bg-amber-500/15',
    category: 'system',
    component: ApiKeyManager,
    permission: 'api_keys',
    defaultWidth: 850,
    defaultHeight: 550,
    minWidth: 500,
    minHeight: 350,
  },
  'backup-manager': {
    id: 'backup-manager',
    title: 'Backups',
    description: 'Backup Management',
    icon: HardDrive,
    iconColor: 'text-slate-400',
    iconBg: 'bg-slate-500/15',
    category: 'system',
    component: BackupManager,
    permission: 'backups',
    defaultWidth: 800,
    defaultHeight: 500,
    minWidth: 500,
    minHeight: 300,
  },
  'gallery': {
    id: 'gallery',
    title: 'Gallery',
    description: 'File Browser',
    icon: FolderOpen,
    iconColor: 'text-pink-400',
    iconBg: 'bg-pink-500/15',
    category: 'system',
    component: Gallery,
    permission: 'gallery',
    defaultWidth: 1100,
    defaultHeight: 700,
    minWidth: 800,
    minHeight: 500,
  },
  'integration-monitor': {
    id: 'integration-monitor',
    title: 'Integrations',
    description: 'Third-party Services',
    icon: Activity,
    iconColor: 'text-teal-400',
    iconBg: 'bg-teal-500/15',
    category: 'system',
    component: IntegrationMonitor,
    permission: 'integrations',
    defaultWidth: 1100,
    defaultHeight: 700,
    minWidth: 800,
    minHeight: 500,
  },
  'vpc-bot': {
    id: 'vpc-bot',
    title: 'VPC Bot',
    description: 'AI Chat Assistant',
    icon: Bot,
    iconColor: 'text-violet-400',
    iconBg: 'bg-gradient-to-br from-violet-500/20 to-indigo-500/20',
    category: 'system',
    component: JarvisChat,
    defaultWidth: 600,
    defaultHeight: 700,
    minWidth: 400,
    minHeight: 500,
  },
  'agent-settings': {
    id: 'agent-settings',
    title: 'AI Agent',
    description: 'Bot Brain & Config',
    icon: Brain,
    iconColor: 'text-purple-400',
    iconBg: 'bg-purple-500/15',
    category: 'system',
    component: AgentSettings,
    permission: 'ai_agent',
    defaultWidth: 950,
    defaultHeight: 650,
    minWidth: 700,
    minHeight: 500,
  },
  'vpc-store': {
    id: 'vpc-store',
    title: 'VPC Store',
    description: 'Download Tools & Extensions',
    icon: Download,
    iconColor: 'text-amber-400',
    iconBg: 'bg-amber-500/15',
    category: 'development',
    component: VpcStore,
    defaultWidth: 1000,
    defaultHeight: 750,
    minWidth: 800,
    minHeight: 600,
  },
  'system-settings': {
    id: 'system-settings',
    title: 'Settings',
    description: 'Themes & Preferences',
    icon: Settings,
    iconColor: 'text-zinc-400',
    iconBg: 'bg-zinc-500/15',
    category: 'system',
    component: SystemSettings,
    defaultWidth: 750,
    defaultHeight: 550,
    minWidth: 600,
    minHeight: 400,
  },
};

export const APP_CATEGORIES = {
  development: { label: 'Development', order: 0 },
  infrastructure: { label: 'Infrastructure', order: 1 },
  system: { label: 'System', order: 2 },
};

export default APP_REGISTRY;
